#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# My site is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

pip install -r requirements.txt
pip install -e .[all]

npm update && npm install --silent -g node-sass@4.9.0 clean-css@3.4.19 uglify-js@2.7.3 requirejs@2.2.0

CWD=`pwd`
invenio npm
python_prefix=$(python -c "import sys; print(sys.prefix)")
cd ${1-$python_prefix}/var/instance/static
npm install
cd ${CWD}
invenio collect -v
invenio assets build
